
export const NodeType = {
  LIBRARY: 'LIBRARY',
  FORM: 'FORM',
  DATATYPE: 'DATATYPE',
  DATAELEMENT: 'DATAELEMENT',
  DATAPOINT: 'DATAPOINT',
  DATAVALUE: 'DATAVALUE',
  MAPPINGPATH: 'MAPPINGPATH',
};

export const EdgeType = {
  LIBRARY_FORM: 'LIBRARY_FORM',
  LIBRARY_DATATYPE: 'LIBRARY_DATATYPE',
  LIBRARY_DATAELEMENT: 'LIBRARY_DATAELEMENT',
  DATAELEMENT_DATATYPE: 'DATAELEMENT_DATATYPE',
  DATAELEMENT_DATAPOINT: 'DATAELEMENT_DATATPOINT',
  DATAPOINT_MAPPINGPATH: 'DATAPOINT_MAPPINGPATH',
  DATAPOINT_DATAVALUE: 'DATAPOINT_DATAVALUE',
};
